version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
    working_directory: /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: make test
      - run: make docker-build
      - run: makr push